version: '3.8'
services:
  db:
    build: src
    container_name: docker-mysql-hands-on
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SFA
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - my-vol:/var/lib/mysql
volumes:
  my-vol:
